Context diagram checksums
DSD-DBS/capella-polarion pull request #125
Opened 2024-10-24 14:46 UTC by micha91

A complete rework of checksums for attachments
requires [this PR](https://github.com/DSD-DBS/capellambse-context-diagrams/pull/147) to be merged first

2024-10-25 11:34 UTC, ewuerger requested changes
Very nice and clean way to check if attachments need an update or not.
There are some minor things that I recognized, mostly about untyped outputs.

A question:
We are using bytes only here and as they are immutable, on any operation of it a new bytes object is created and stored in memory. How often do we actually read images from their path to receive the bytes? With `io.BytesIO` there is an improvement in speed and memory allocation (can be neglected I think) for the read operations. But if we don't do that so often there is no performance gain here, switching from just handling bytes to handling an `io.BytesIO` object.

After solving the requests, you'll get my approval.

2024-10-25 11:34 UTC, ewuerger commented on capella2polarion/data_model/work_item_attachments.py
> +    def content_bytes(self):
Output isn't typed. 
```suggestion
    def content_bytes(self) -> bytes:
```

2024-10-25 11:34 UTC, ewuerger commented on capella2polarion/data_model/work_item_attachments.py
> +    def content_checksum(self):
```suggestion
    def content_checksum(self) -> str:
```

2024-10-25 11:34 UTC, ewuerger commented on capella2polarion/data_model/work_item_attachments.py
> +    def content_bytes(self):
```suggestion
    def content_bytes(self) -> bytes:
```

2024-10-25 11:34 UTC, ewuerger commented on capella2polarion/data_model/work_items.py
> +    def _calculate_attachment_checksums(self):
Please type it, bonus points for inventing a Type-Alias.

2024-10-25 12:00 UTC, micha91 commented
> A question: We are using bytes only here and as they are immutable, on any operation of it a new bytes object is created and stored in memory. How often do we actually read images from their path to receive the bytes? With `io.BytesIO` there is an improvement in speed and memory allocation (can be neglected I think) for the read operations. But if we don't do that so often there is no performance gain here, switching from just handling bytes to handling an `io.BytesIO` object.

We only read files from disk when we create the attachment. The changes with the dynamic generation of the content only affect diagrams and in this case we also cache the result in `_content_bytes` so that also diagrams are only generated/loaded from disk once.

2024-10-29 14:58 UTC, ewuerger approved these changes
LGTM.

2024-10-29 16:37 UTC, merged